<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.bestsellerResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/bestsellerResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\common\Image getTopBanner()
 * @method void setTopBanner(\service\message\common\Image $value)
 * @method array getBlocks()
 * @method void appendBlocks(\service\message\common\CategoryProductBlock $value)
 */
class bestsellerResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.bestsellerResponse)
  
  /**
   * @var \service\message\common\Image $top_banner
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $top_banner;
  
  /**
   * @var array $blocks
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\CategoryProductBlock
   **/
  protected $blocks;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.bestsellerResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.bestsellerResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "top_banner",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Image',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "blocks",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\CategoryProductBlock',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.bestsellerResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
