<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.getAreaBrandResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/getAreaBrandResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getBrandList()
 * @method void appendBrandList(\string $value)
 */
class getAreaBrandResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.getAreaBrandResponse)
  
  /**
   * @var array $brand_list
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $brand_list;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.getAreaBrandResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.getAreaBrandResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "brand_list",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.getAreaBrandResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
