<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.getProductResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/getProductResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getProductList()
 * @method void appendProductList(\service\message\common\Product $value)
 * @method \service\message\common\Store getWholesalerInfo()
 * @method void setWholesalerInfo(\service\message\common\Store $value)
 */
class getProductResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.getProductResponse)
  
  /**
   * @var array $product_list
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Product
   **/
  protected $product_list;
  
  /**
   * @var \service\message\common\Store $wholesaler_info
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $wholesaler_info;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.getProductResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.getProductResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "product_list",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Product',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "wholesaler_info",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Store',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.getProductResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
