<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.getStoresByAreaIdsResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/getStoresByAreaIdsResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getWholesalerList()
 * @method void appendWholesalerList(\service\message\common\Store $value)
 */
class getStoresByAreaIdsResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.getStoresByAreaIdsResponse)
  
  /**
   * @var array $wholesaler_list
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Store
   **/
  protected $wholesaler_list;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.getStoresByAreaIdsResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.getStoresByAreaIdsResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "wholesaler_list",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Store',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.getStoresByAreaIdsResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
