<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.HomePageConfig)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/HomePageConfig.proto
 *
 * -*- magic methods -*-
 *
 * @method array getTopicBlocks()
 * @method void appendTopicBlocks(\service\message\common\TopicBlock $value)
 * @method array getProductBlocks()
 * @method void appendProductBlocks(\service\message\common\ProductBlock $value)
 * @method \service\message\common\BrandBlock getBrandBlock()
 * @method void setBrandBlock(\service\message\common\BrandBlock $value)
 */
class HomePageConfig extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.HomePageConfig)
  
  /**
   * @var array $topic_blocks
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\TopicBlock
   **/
  protected $topic_blocks;
  
  /**
   * @var array $product_blocks
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\ProductBlock
   **/
  protected $product_blocks;
  
  /**
   * @var \service\message\common\BrandBlock $brand_block
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $brand_block;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.HomePageConfig)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.HomePageConfig)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "topic_blocks",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\TopicBlock',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "product_blocks",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\ProductBlock',
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "brand_block",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\BrandBlock',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.HomePageConfig)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
