<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.SaleRuleRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/SaleRuleRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method array getRuleId()
 * @method void appendRuleId(\string $value)
 * @method array getWholesalerId()
 * @method void appendWholesalerId(\string $value)
 */
class SaleRuleRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.SaleRuleRequest)
  
  /**
   * @var array $rule_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $rule_id;
  
  /**
   * @var array $wholesaler_id
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $wholesaler_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.SaleRuleRequest)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.SaleRuleRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "rule_id",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "wholesaler_id",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.SaleRuleRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
