<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.SaleRuleResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/SaleRuleResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getPromotions()
 * @method void appendPromotions(\service\message\common\PromotionRule $value)
 */
class SaleRuleResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.SaleRuleResponse)
  
  /**
   * @var array $promotions
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\PromotionRule
   **/
  protected $promotions;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.SaleRuleResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.SaleRuleResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "promotions",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\PromotionRule',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.SaleRuleResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
