<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.tipsResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/tipsResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getTitle()
 * @method void setTitle(\string $value)
 * @method string getContent()
 * @method void setContent(\string $value)
 */
class tipsResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.tipsResponse)
  
  /**
   * @var string $title
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $title;
  
  /**
   * @var string $content
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $content;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.tipsResponse)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.tipsResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "title",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "content",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.tipsResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
