<?php
namespace service\message\merchant;

// @@protoc_insertion_point(namespace:.service.message.merchant.tipsRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: merchant/tipsRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getIdentifier()
 * @method void setIdentifier(\string $value)
 * @method string getFormat()
 * @method void setFormat(\string $value)
 */
class tipsRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.merchant.tipsRequest)
  
  /**
   * @var string $identifier
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $identifier;
  
  /**
   * @var string $format
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $format;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.merchant.tipsRequest)

  // @@protoc_insertion_point(class_scope:.service.message.merchant.tipsRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "identifier",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "format",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.merchant.tipsRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
