<?php
namespace service\message\customer;

// @@protoc_insertion_point(namespace:.service.message.customer.CartItemsResponse2)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: customer/CartItemsResponse2.proto
 *
 * -*- magic methods -*-
 *
 * @method array getData()
 * @method void appendData(\service\message\common\CartItem2 $value)
 */
class CartItemsResponse2 extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.customer.CartItemsResponse2)
  
  /**
   * @var array $data
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\CartItem2
   **/
  protected $data;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.customer.CartItemsResponse2)

  // @@protoc_insertion_point(class_scope:.service.message.customer.CartItemsResponse2)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "data",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\CartItem2',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.customer.CartItemsResponse2)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
