<?php
namespace service\message\customer;

// @@protoc_insertion_point(namespace:.service.message.customer.CheckCustomerRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: customer/CheckCustomerRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getField()
 * @method void setField(\string $value)
 * @method string getUsername()
 * @method void setUsername(\string $value)
 * @method string getPhone()
 * @method void setPhone(\string $value)
 */
class CheckCustomerRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.customer.CheckCustomerRequest)
  
  /**
   * @var string $field
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $field;
  
  /**
   * @var string $username
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $username;
  
  /**
   * @var string $phone
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $phone;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.customer.CheckCustomerRequest)

  // @@protoc_insertion_point(class_scope:.service.message.customer.CheckCustomerRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "field",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "username",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "phone",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.customer.CheckCustomerRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
