<?php
namespace service\message\customer;

// @@protoc_insertion_point(namespace:.service.message.customer.GetAppVersionRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: customer/GetAppVersionRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getSystem()
 * @method void setSystem(\string $value)
 * @method string getPlatform()
 * @method void setPlatform(\string $value)
 * @method string getChannel()
 * @method void setChannel(\string $value)
 * @method string getVersion()
 * @method void setVersion(\string $value)
 */
class GetAppVersionRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.customer.GetAppVersionRequest)
  
  /**
   * @var string $system
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $system;
  
  /**
   * @var string $platform
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $platform;
  
  /**
   * @var string $channel
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $channel;
  
  /**
   * @var string $version
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $version;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.customer.GetAppVersionRequest)

  // @@protoc_insertion_point(class_scope:.service.message.customer.GetAppVersionRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "system",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "platform",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "channel",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "version",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.customer.GetAppVersionRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
