<?php
namespace service\message\customer;

// @@protoc_insertion_point(namespace:.service.message.customer.GetAppVersionResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: customer/GetAppVersionResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getTitle()
 * @method void setTitle(\string $value)
 * @method string getUrl()
 * @method void setUrl(\string $value)
 * @method string getVersion()
 * @method void setVersion(\string $value)
 * @method string getDescription()
 * @method void setDescription(\string $value)
 * @method string getType()
 * @method void setType(\string $value)
 */
class GetAppVersionResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.customer.GetAppVersionResponse)
  
  /**
   * @var string $title
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $title;
  
  /**
   * @var string $url
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $url;
  
  /**
   * @var string $version
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $version;
  
  /**
   * @var string $description
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $description;
  
  /**
   * @var string $type
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $type;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.customer.GetAppVersionResponse)

  // @@protoc_insertion_point(class_scope:.service.message.customer.GetAppVersionResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "title",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "url",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "version",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "description",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "type",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.customer.GetAppVersionResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
