<?php
namespace service\message\customer;

// @@protoc_insertion_point(namespace:.service.message.customer.TestReportRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: customer/TestReportRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getIp()
 * @method void setIp(\string $value)
 */
class TestReportRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.customer.TestReportRequest)
  
  /**
   * @var string $ip
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $ip;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.customer.TestReportRequest)

  // @@protoc_insertion_point(class_scope:.service.message.customer.TestReportRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "ip",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.customer.TestReportRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
