<?php
namespace service\message\core;

// @@protoc_insertion_point(namespace:.service.message.core.ConfigRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: core/ConfigRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getSystem()
 * @method void setSystem(\string $value)
 * @method string getChannel()
 * @method void setChannel(\string $value)
 * @method string getVer()
 * @method void setVer(\string $value)
 */
class ConfigRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.core.ConfigRequest)
  
  /**
   * @var string $system
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $system;
  
  /**
   * @var string $channel
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $channel;
  
  /**
   * @var string $ver
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $ver;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.core.ConfigRequest)

  // @@protoc_insertion_point(class_scope:.service.message.core.ConfigRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "system",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "channel",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "ver",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.core.ConfigRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
