<?php
namespace service\message\core;

// @@protoc_insertion_point(namespace:.service.message.core.FetchRouteResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: core/FetchRouteResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getServices()
 * @method void appendServices(\service\message\common\Service $value)
 * @method array getMapping()
 * @method void appendMapping(\service\message\common\KeyValueItem $value)
 * @method bool getShortTcp()
 * @method void setShortTcp(bool $value)
 */
class FetchRouteResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.core.FetchRouteResponse)
  
  /**
   * @var array $services
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Service
   **/
  protected $services;
  
  /**
   * @var array $mapping
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\KeyValueItem
   **/
  protected $mapping;
  
  /**
   * @var bool $short_tcp
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_BOOL
   **/
  protected $short_tcp;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.core.FetchRouteResponse)

  // @@protoc_insertion_point(class_scope:.service.message.core.FetchRouteResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "services",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Service',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "mapping",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\KeyValueItem',
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "short_tcp",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.core.FetchRouteResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
