<?php
namespace service\message\core;

// @@protoc_insertion_point(namespace:.service.message.core.FetchRouteRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: core/FetchRouteRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getAuthToken()
 * @method void setAuthToken(\string $value)
 */
class FetchRouteRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.core.FetchRouteRequest)
  
  /**
   * @var string $auth_token
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $auth_token;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.core.FetchRouteRequest)

  // @@protoc_insertion_point(class_scope:.service.message.core.FetchRouteRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "auth_token",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.core.FetchRouteRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
