<?php
namespace service\message\core;

// @@protoc_insertion_point(namespace:.service.message.core.getWholesalerResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: core/getWholesalerResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getWholesalerIds()
 * @method void appendWholesalerIds(\string $value)
 */
class getWholesalerResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.core.getWholesalerResponse)
  
  /**
   * @var array $wholesaler_ids
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $wholesaler_ids;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.core.getWholesalerResponse)

  // @@protoc_insertion_point(class_scope:.service.message.core.getWholesalerResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "wholesaler_ids",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.core.getWholesalerResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
