<?php
namespace service\message\syncProcess;

// @@protoc_insertion_point(namespace:.service.message.syncProcess.SubmitResult)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: syncProcess/SubmitResult.proto
 *
 * -*- magic methods -*-
 *
 * @method string getSubmitId()
 * @method void setSubmitId(\string $value)
 * @method \service\message\syncProcess\Status getStatus()
 * @method void setStatus(\service\message\syncProcess\Status $value)
 * @method string getCode()
 * @method void setCode(\string $value)
 * @method string getMessage()
 * @method void setMessage(\string $value)
 */
class SubmitResult extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.syncProcess.SubmitResult)
  
  /**
   * @var string $submit_id
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $submit_id;
  
  /**
   * @var \service\message\syncProcess\Status $status
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_ENUM
   * @see \service\message\syncProcess\Status
   **/
  protected $status;
  
  /**
   * @var string $code
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $code;
  
  /**
   * @var string $message
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $message;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.syncProcess.SubmitResult)

  // @@protoc_insertion_point(class_scope:.service.message.syncProcess.SubmitResult)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "submit_id",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "status",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "code",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "message",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.syncProcess.SubmitResult)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
