<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.BrandBlock)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/BrandBlock.proto
 *
 * -*- magic methods -*-
 *
 * @method array getBrands()
 * @method void appendBrands(\service\message\common\Brand $value)
 * @method string getSort()
 * @method void setSort(\string $value)
 */
class BrandBlock extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.BrandBlock)
  
  /**
   * @var array $brands
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Brand
   **/
  protected $brands;
  
  /**
   * @var string $sort
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $sort;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.BrandBlock)

  // @@protoc_insertion_point(class_scope:.service.message.common.BrandBlock)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "brands",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Brand',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "sort",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.BrandBlock)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
