<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Brand)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Brand.proto
 *
 * -*- magic methods -*-
 *
 * @method string getBrandId()
 * @method void setBrandId(\string $value)
 * @method string getName()
 * @method void setName(\string $value)
 * @method string getIcon()
 * @method void setIcon(\string $value)
 */
class Brand extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Brand)
  
  /**
   * @var string $brand_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $brand_id;
  
  /**
   * @var string $name
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $name;
  
  /**
   * @var string $icon
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $icon;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Brand)

  // @@protoc_insertion_point(class_scope:.service.message.common.Brand)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "brand_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "icon",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Brand)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
