<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.City)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/City.proto
 *
 * -*- magic methods -*-
 *
 * @method string getProvinceName()
 * @method void setProvinceName(\string $value)
 * @method string getProvinceCode()
 * @method void setProvinceCode(\string $value)
 * @method string getCityName()
 * @method void setCityName(\string $value)
 * @method string getCityCode()
 * @method void setCityCode(\string $value)
 */
class City extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.City)
  
  /**
   * @var string $province_name
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $province_name;
  
  /**
   * @var string $province_code
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $province_code;
  
  /**
   * @var string $city_name
   * @tag 3
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $city_name;
  
  /**
   * @var string $city_code
   * @tag 4
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $city_code;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.City)

  // @@protoc_insertion_point(class_scope:.service.message.common.City)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "province_name",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "province_code",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "city_name",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "city_code",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.City)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
