<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.ContractorStatics)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/ContractorStatics.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\common\SalesCountStatics getSalesCount()
 * @method void setSalesCount(\service\message\common\SalesCountStatics $value)
 * @method array getDatas()
 * @method void appendDatas(\service\message\common\DataInfo $value)
 */
class ContractorStatics extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.ContractorStatics)
  
  /**
   * @var \service\message\common\SalesCountStatics $sales_count
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $sales_count;
  
  /**
   * @var array $datas
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\DataInfo
   **/
  protected $datas;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.ContractorStatics)

  // @@protoc_insertion_point(class_scope:.service.message.common.ContractorStatics)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "sales_count",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\SalesCountStatics',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "datas",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\DataInfo',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.ContractorStatics)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
