<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Coupon)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Coupon.proto
 *
 * 优惠券
 *
 * -*- magic methods -*-
 *
 * @method string getEntityId()
 * @method void setEntityId(\string $value)
 * @method string getCustomerId()
 * @method void setCustomerId(\string $value)
 * @method string getState()
 * @method void setState(\string $value)
 * @method string getRuleId()
 * @method void setRuleId(\string $value)
 * @method string getExpirationDate()
 * @method void setExpirationDate(\string $value)
 * @method string getSource()
 * @method void setSource(\string $value)
 * @method string getCreatedAt()
 * @method void setCreatedAt(\string $value)
 * @method string getCouponTitle()
 * @method void setCouponTitle(\string $value)
 * @method string getFrontnote()
 * @method void setFrontnote(\string $value)
 * @method string getDiscountType()
 * @method void setDiscountType(\string $value)
 * @method string getDiscount()
 * @method void setDiscount(\string $value)
 * @method string getUseCondition()
 * @method void setUseCondition(\string $value)
 * @method string getUnavailableReason()
 * @method void setUnavailableReason(\string $value)
 * @method string getUrl()
 * @method void setUrl(\string $value)
 * @method string getIsSoonExpire()
 * @method void setIsSoonExpire(\string $value)
 */
class Coupon extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Coupon)
  
  /**
   * @var string $entity_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   *
   * 优惠券ID
   *
   **/
  protected $entity_id;
  
  /**
   * @var string $customer_id
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   *
   * 用户ID
   *
   **/
  protected $customer_id;
  
  /**
   * @var string $state
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   *
   * 优惠券状态
   *
   **/
  protected $state;
  
  /**
   * @var string $rule_id
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   *
   * 规则ID
   *
   **/
  protected $rule_id;
  
  /**
   * @var string $expiration_date
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 过期时间
   *
   **/
  protected $expiration_date;
  
  /**
   * @var string $source
   * @tag 6
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   *
   * 来源
   *
   **/
  protected $source;
  
  /**
   * @var string $created_at
   * @tag 7
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 领取时间
   *
   **/
  protected $created_at;
  
  /**
   * @var string $coupon_title
   * @tag 8
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 优惠券标题
   *
   **/
  protected $coupon_title;
  
  /**
   * @var string $frontnote
   * @tag 9
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 优惠券描述
   *
   **/
  protected $frontnote;
  
  /**
   * @var string $discount_type
   * @tag 10
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   *
   * 减免送类型  1、减额 2、折扣 3、赠送
   *
   **/
  protected $discount_type;
  
  /**
   * @var string $discount
   * @tag 11
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 优惠结果 可能为：减额 折扣 赠送
   *
   **/
  protected $discount;
  
  /**
   * @var string $use_condition
   * @tag 12
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 使用条件
   *
   **/
  protected $use_condition;
  
  /**
   * @var string $unavailable_reason
   * @tag 13
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 不可使用原因
   *
   **/
  protected $unavailable_reason;
  
  /**
   * @var string $url
   * @tag 14
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   *
   * 优惠券列表跳转链接
   *
   **/
  protected $url;
  
  /**
   * @var string $is_soon_expire
   * @tag 15
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   *
   * 是否即将过期
   *
   **/
  protected $is_soon_expire;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Coupon)

  // @@protoc_insertion_point(class_scope:.service.message.common.Coupon)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "entity_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "customer_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "state",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "rule_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "expiration_date",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "source",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "created_at",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "coupon_title",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "frontnote",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "discount_type",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "discount",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(12, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "use_condition",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(13, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "unavailable_reason",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(14, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "url",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(15, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "is_soon_expire",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Coupon)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
