<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.DataInfo)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/DataInfo.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName(\string $value)
 * @method array getData()
 * @method void appendData(\service\message\common\KeyValueItem $value)
 */
class DataInfo extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.DataInfo)
  
  /**
   * @var string $name
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $name;
  
  /**
   * @var array $data
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\KeyValueItem
   **/
  protected $data;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.DataInfo)

  // @@protoc_insertion_point(class_scope:.service.message.common.DataInfo)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "data",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\KeyValueItem',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.DataInfo)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
