<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.DiscountNote)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/DiscountNote.proto
 *
 * -*- magic methods -*-
 *
 * @method string getWholesalerId()
 * @method void setWholesalerId(\string $value)
 * @method array getPromotions()
 * @method void appendPromotions(\service\message\common\PromotionInfo $value)
 */
class DiscountNote extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.DiscountNote)
  
  /**
   * @var string $wholesaler_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $wholesaler_id;
  
  /**
   * @var array $promotions
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\PromotionInfo
   **/
  protected $promotions;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.DiscountNote)

  // @@protoc_insertion_point(class_scope:.service.message.common.DiscountNote)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "wholesaler_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "promotions",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\PromotionInfo',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.DiscountNote)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
