<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Image)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Image.proto
 *
 * -*- magic methods -*-
 *
 * @method string getSrc()
 * @method void setSrc(\string $value)
 * @method string getHref()
 * @method void setHref(\string $value)
 * @method string getHeight()
 * @method void setHeight(\string $value)
 */
class Image extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Image)
  
  /**
   * @var string $src
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $src;
  
  /**
   * @var string $href
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $href;
  
  /**
   * @var string $height
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $height;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Image)

  // @@protoc_insertion_point(class_scope:.service.message.common.Image)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "src",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "href",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "height",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Image)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
