<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.OrderItem)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/OrderItem.proto
 *
 * -*- magic methods -*-
 *
 * @method string getItemId()
 * @method void setItemId(\string $value)
 * @method string getName()
 * @method void setName(\string $value)
 * @method string getPrice()
 * @method void setPrice(\string $value)
 * @method string getQty()
 * @method void setQty(\string $value)
 * @method string getImage()
 * @method void setImage(\string $value)
 * @method string getProductId()
 * @method void setProductId(\string $value)
 * @method string getBarcode()
 * @method void setBarcode(\string $value)
 * @method string getOriginalPrice()
 * @method void setOriginalPrice(\string $value)
 * @method string getRowTotal()
 * @method void setRowTotal(\string $value)
 * @method string getSpecification()
 * @method void setSpecification(\string $value)
 * @method array getTags()
 * @method void appendTags(\service\message\common\Tag $value)
 * @method string getRebatesAll()
 * @method void setRebatesAll(\string $value)
 * @method string getReceipt()
 * @method void setReceipt(\string $value)
 */
class OrderItem extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.OrderItem)
  
  /**
   * @var string $item_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $item_id;
  
  /**
   * @var string $name
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $name;
  
  /**
   * @var string $price
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $price;
  
  /**
   * @var string $qty
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $qty;
  
  /**
   * @var string $image
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $image;
  
  /**
   * @var string $product_id
   * @tag 6
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $product_id;
  
  /**
   * @var string $barcode
   * @tag 7
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $barcode;
  
  /**
   * @var string $original_price
   * @tag 8
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $original_price;
  
  /**
   * @var string $row_total
   * @tag 9
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $row_total;
  
  /**
   * @var string $specification
   * @tag 10
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $specification;
  
  /**
   * @var array $tags
   * @tag 11
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Tag
   **/
  protected $tags;
  
  /**
   * @var string $rebates_all
   * @tag 12
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $rebates_all;
  
  /**
   * @var string $receipt
   * @tag 13
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $receipt;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.OrderItem)

  // @@protoc_insertion_point(class_scope:.service.message.common.OrderItem)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "item_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "price",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "qty",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "image",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "product_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "barcode",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "original_price",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "row_total",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "specification",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "tags",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Tag',
      )));
      $desc->addField(12, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "rebates_all",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(13, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "receipt",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.OrderItem)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
