<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Pagination)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Pagination.proto
 *
 * -*- magic methods -*-
 *
 * @method string getTotalCount()
 * @method void setTotalCount(\string $value)
 * @method string getPage()
 * @method void setPage(\string $value)
 * @method string getLastPage()
 * @method void setLastPage(\string $value)
 * @method string getPageSize()
 * @method void setPageSize(\string $value)
 */
class Pagination extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Pagination)
  
  /**
   * @var string $total_count
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $total_count;
  
  /**
   * @var string $page
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $page;
  
  /**
   * @var string $last_page
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $last_page;
  
  /**
   * @var string $page_size
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $page_size;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Pagination)

  // @@protoc_insertion_point(class_scope:.service.message.common.Pagination)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "total_count",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "page",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "last_page",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "page_size",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Pagination)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
