<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.PromotionInfo)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/PromotionInfo.proto
 *
 * -*- magic methods -*-
 *
 * @method string getText()
 * @method void setText(\string $value)
 * @method string getDescription()
 * @method void setDescription(\string $value)
 * @method string getRebatesWholesaler()
 * @method void setRebatesWholesaler(\string $value)
 * @method string getRebatesLelai()
 * @method void setRebatesLelai(\string $value)
 * @method string getOffMoney()
 * @method void setOffMoney(\string $value)
 */
class PromotionInfo extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.PromotionInfo)
  
  /**
   * @var string $text
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $text;
  
  /**
   * @var string $description
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $description;
  
  /**
   * @var string $rebates_wholesaler
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $rebates_wholesaler;
  
  /**
   * @var string $rebates_lelai
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $rebates_lelai;
  
  /**
   * @var string $off_money
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $off_money;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.PromotionInfo)

  // @@protoc_insertion_point(class_scope:.service.message.common.PromotionInfo)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "text",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "description",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "rebates_wholesaler",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "rebates_lelai",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "off_money",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.PromotionInfo)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
