<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Protocol)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Protocol.proto
 *
 */
class Protocol extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.service.message.common.Protocol)
  
  const PB = 1;
  const JSON = 2;
  
  // @@protoc_insertion_point(const_scope:.service.message.common.Protocol)
  
  // @@protoc_insertion_point(class_scope:.service.message.common.Protocol)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::PB,
        "name"  => 'PB',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::JSON,
        "name"  => 'JSON',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Protocol)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
