<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Rule)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Rule.proto
 *
 * -*- magic methods -*-
 *
 * @method string getCondition()
 * @method void setCondition(\string $value)
 * @method string getOff()
 * @method void setOff(\string $value)
 */
class Rule extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Rule)
  
  /**
   * @var string $condition
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $condition;
  
  /**
   * @var string $off
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $off;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Rule)

  // @@protoc_insertion_point(class_scope:.service.message.common.Rule)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "condition",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "off",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Rule)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
