<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Server)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Server.proto
 *
 * -*- magic methods -*-
 *
 * @method string getMemory()
 * @method void setMemory(\string $value)
 * @method string getCpu()
 * @method void setCpu(\string $value)
 * @method string getCores()
 * @method void setCores(\string $value)
 * @method array getLoads()
 * @method void appendLoads(\string $value)
 * @method string getIp()
 * @method void setIp(\string $value)
 */
class Server extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Server)
  
  /**
   * @var string $memory
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $memory;
  
  /**
   * @var string $cpu
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $cpu;
  
  /**
   * @var string $cores
   * @tag 3
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $cores;
  
  /**
   * @var array $loads
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $loads;
  
  /**
   * @var string $ip
   * @tag 5
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $ip;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Server)

  // @@protoc_insertion_point(class_scope:.service.message.common.Server)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "memory",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "cpu",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "cores",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "loads",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "ip",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Server)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
