<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Thematic)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Thematic.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\common\Store getStore()
 * @method void setStore(\service\message\common\Store $value)
 * @method array getProducts()
 * @method void appendProducts(\service\message\common\Product $value)
 */
class Thematic extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Thematic)
  
  /**
   * @var \service\message\common\Store $store
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $store;
  
  /**
   * @var array $products
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Product
   **/
  protected $products;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Thematic)

  // @@protoc_insertion_point(class_scope:.service.message.common.Thematic)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "store",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Store',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "products",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Product',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Thematic)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
