<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.WechatPay)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/WechatPay.proto
 *
 * -*- magic methods -*-
 *
 * @method string getPrepayId()
 * @method void setPrepayId(\string $value)
 * @method string getNonceStr()
 * @method void setNonceStr(\string $value)
 * @method string getTimeStamp()
 * @method void setTimeStamp(\string $value)
 * @method string getPackage()
 * @method void setPackage(\string $value)
 * @method string getSign()
 * @method void setSign(\string $value)
 */
class WechatPay extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.WechatPay)
  
  /**
   * @var string $prepay_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $prepay_id;
  
  /**
   * @var string $nonce_str
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $nonce_str;
  
  /**
   * @var string $time_stamp
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $time_stamp;
  
  /**
   * @var string $package
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $package;
  
  /**
   * @var string $sign
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $sign;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.WechatPay)

  // @@protoc_insertion_point(class_scope:.service.message.common.WechatPay)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "prepay_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "nonce_str",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "time_stamp",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "sign",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.WechatPay)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
