<?php
namespace service\message\contractor;

// @@protoc_insertion_point(namespace:.service.message.contractor.GetAreaByLngLatResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: contractor/GetAreaByLngLatResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getAreaId()
 * @method void setAreaId(\string $value)
 */
class GetAreaByLngLatResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.contractor.GetAreaByLngLatResponse)
  
  /**
   * @var string $area_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $area_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.contractor.GetAreaByLngLatResponse)

  // @@protoc_insertion_point(class_scope:.service.message.contractor.GetAreaByLngLatResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "area_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.contractor.GetAreaByLngLatResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
