<?php
namespace service\message\contractor;

// @@protoc_insertion_point(namespace:.service.message.contractor.MarkPriceProductListResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: contractor/MarkPriceProductListResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method array getProductList()
 * @method void appendProductList(\service\message\common\MarkPriceProduct $value)
 * @method \service\message\common\Pagination getPages()
 * @method void setPages(\service\message\common\Pagination $value)
 */
class MarkPriceProductListResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.contractor.MarkPriceProductListResponse)
  
  /**
   * @var array $product_list
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\MarkPriceProduct
   **/
  protected $product_list;
  
  /**
   * @var \service\message\common\Pagination $pages
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $pages;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.contractor.MarkPriceProductListResponse)

  // @@protoc_insertion_point(class_scope:.service.message.contractor.MarkPriceProductListResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "product_list",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\MarkPriceProduct',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "pages",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Pagination',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.contractor.MarkPriceProductListResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
