<?php
namespace service\message\contractor;

// @@protoc_insertion_point(namespace:.service.message.contractor.StoreRecentlyOrderRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: contractor/StoreRecentlyOrderRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getCustomerId()
 * @method void setCustomerId(\string $value)
 */
class StoreRecentlyOrderRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.contractor.StoreRecentlyOrderRequest)
  
  /**
   * @var string $customer_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $customer_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.contractor.StoreRecentlyOrderRequest)

  // @@protoc_insertion_point(class_scope:.service.message.contractor.StoreRecentlyOrderRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "customer_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.contractor.StoreRecentlyOrderRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
