<?php
namespace service\message\sales;

// @@protoc_insertion_point(namespace:.service.message.sales.customerOrderStatItem)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sales/customerOrderStatItem.proto
 *
 * -*- magic methods -*-
 *
 * @method string getYearMonth()
 * @method void setYearMonth(\string $value)
 * @method string getSumGrandTotal()
 * @method void setSumGrandTotal(\string $value)
 * @method string getOrderCount()
 * @method void setOrderCount(\string $value)
 */
class customerOrderStatItem extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sales.customerOrderStatItem)
  
  /**
   * @var string $year_month
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $year_month;
  
  /**
   * @var string $sum_grand_total
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $sum_grand_total;
  
  /**
   * @var string $order_count
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $order_count;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sales.customerOrderStatItem)

  // @@protoc_insertion_point(class_scope:.service.message.sales.customerOrderStatItem)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "year_month",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "sum_grand_total",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "order_count",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sales.customerOrderStatItem)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
