<?php
namespace service\message\sales;

// @@protoc_insertion_point(namespace:.service.message.sales.DriverOrderCollectionRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sales/DriverOrderCollectionRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method array getOrderIds()
 * @method void appendOrderIds(\string $value)
 * @method string getFuzzyIncrementId()
 * @method void setFuzzyIncrementId(\string $value)
 * @method array getWholesalerId()
 * @method void appendWholesalerId(\string $value)
 */
class DriverOrderCollectionRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sales.DriverOrderCollectionRequest)
  
  /**
   * @var array $order_ids
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $order_ids;
  
  /**
   * @var string $fuzzy_increment_id
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $fuzzy_increment_id;
  
  /**
   * @var array $wholesaler_id
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $wholesaler_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sales.DriverOrderCollectionRequest)

  // @@protoc_insertion_point(class_scope:.service.message.sales.DriverOrderCollectionRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "order_ids",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "fuzzy_increment_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "wholesaler_id",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sales.DriverOrderCollectionRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
