<?php
namespace service\message\sales;

// @@protoc_insertion_point(namespace:.service.message.sales.getCustomerOrderStatResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sales/getCustomerOrderStatResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\sales\customerOrderStatItem getStatAll()
 * @method void setStatAll(\service\message\sales\customerOrderStatItem $value)
 * @method array getStatList()
 * @method void appendStatList(\service\message\sales\customerOrderStatItem $value)
 */
class getCustomerOrderStatResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sales.getCustomerOrderStatResponse)
  
  /**
   * @var \service\message\sales\customerOrderStatItem $stat_all
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $stat_all;
  
  /**
   * @var array $stat_list
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\sales\customerOrderStatItem
   **/
  protected $stat_list;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sales.getCustomerOrderStatResponse)

  // @@protoc_insertion_point(class_scope:.service.message.sales.getCustomerOrderStatResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "stat_all",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\sales\customerOrderStatItem',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "stat_list",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\sales\customerOrderStatItem',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sales.getCustomerOrderStatResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
