<?php
namespace service\message\sales;

// @@protoc_insertion_point(namespace:.service.message.sales.OrderReviewResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sales/OrderReviewResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getGrandTotal()
 * @method void setGrandTotal(\string $value)
 * @method string getShippingAmount()
 * @method void setShippingAmount(\string $value)
 * @method string getDiscountAmount()
 * @method void setDiscountAmount(\string $value)
 * @method string getCustomerId()
 * @method void setCustomerId(\string $value)
 * @method array getItems()
 * @method void appendItems(\service\message\common\Order $value)
 * @method string getBalance()
 * @method void setBalance(\string $value)
 * @method \service\message\common\TagGroup getAppliedRules()
 * @method void setAppliedRules(\service\message\common\TagGroup $value)
 * @method string getBaseTotal()
 * @method void setBaseTotal(\string $value)
 * @method string getCouponDiscountAmount()
 * @method void setCouponDiscountAmount(\string $value)
 * @method string getCouponHelpUrl()
 * @method void setCouponHelpUrl(\string $value)
 * @method array getAvailableCoupons()
 * @method void appendAvailableCoupons(\service\message\common\Coupon $value)
 * @method array getUnavailableCoupons()
 * @method void appendUnavailableCoupons(\service\message\common\Coupon $value)
 * @method string getCouponId()
 * @method void setCouponId(\string $value)
 * @method string getCouponText()
 * @method void setCouponText(\string $value)
 */
class OrderReviewResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sales.OrderReviewResponse)
  
  /**
   * @var string $grand_total
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $grand_total;
  
  /**
   * @var string $shipping_amount
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $shipping_amount;
  
  /**
   * @var string $discount_amount
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $discount_amount;
  
  /**
   * @var string $customer_id
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $customer_id;
  
  /**
   * @var array $items
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Order
   **/
  protected $items;
  
  /**
   * @var string $balance
   * @tag 6
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $balance;
  
  /**
   * @var \service\message\common\TagGroup $applied_rules
   * @tag 7
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $applied_rules;
  
  /**
   * @var string $base_total
   * @tag 8
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $base_total;
  
  /**
   * @var string $coupon_discount_amount
   * @tag 9
   * @label optional
   * @type \ProtocolBuffers::TYPE_FLOAT
   **/
  protected $coupon_discount_amount;
  
  /**
   * @var string $coupon_help_url
   * @tag 10
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $coupon_help_url;
  
  /**
   * @var array $available_coupons
   * @tag 11
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Coupon
   **/
  protected $available_coupons;
  
  /**
   * @var array $unavailable_coupons
   * @tag 12
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\common\Coupon
   **/
  protected $unavailable_coupons;
  
  /**
   * @var string $coupon_id
   * @tag 13
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $coupon_id;
  
  /**
   * @var string $coupon_text
   * @tag 14
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $coupon_text;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sales.OrderReviewResponse)

  // @@protoc_insertion_point(class_scope:.service.message.sales.OrderReviewResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "grand_total",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "shipping_amount",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "discount_amount",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "customer_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "items",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Order',
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "balance",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "applied_rules",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\TagGroup',
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "base_total",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_FLOAT,
        "name"     => "coupon_discount_amount",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "coupon_help_url",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "available_coupons",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Coupon',
      )));
      $desc->addField(12, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "unavailable_coupons",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Coupon',
      )));
      $desc->addField(13, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "coupon_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(14, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "coupon_text",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sales.OrderReviewResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
