<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.Cmd)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/Cmd.proto
 *
 * -*- magic methods -*-
 *
 * @method string getCmd()
 * @method void setCmd(\string $value)
 * @method string getScope()
 * @method void setScope(\string $value)
 */
class Cmd extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sync.Cmd)
  
  /**
   * @var string $cmd
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $cmd;
  
  /**
   * @var string $scope
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $scope;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sync.Cmd)

  // @@protoc_insertion_point(class_scope:.service.message.sync.Cmd)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "cmd",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "scope",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.Cmd)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
