<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.GetTerminalNoRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/GetTerminalNoRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getCustomerId()
 * @method void setCustomerId(\string $value)
 * @method string getAuthToken()
 * @method void setAuthToken(\string $value)
 * @method string getDeviceId()
 * @method void setDeviceId(\string $value)
 */
class GetTerminalNoRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sync.GetTerminalNoRequest)
  
  /**
   * @var string $customer_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $customer_id;
  
  /**
   * @var string $auth_token
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $auth_token;
  
  /**
   * @var string $device_id
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $device_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sync.GetTerminalNoRequest)

  // @@protoc_insertion_point(class_scope:.service.message.sync.GetTerminalNoRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "customer_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "auth_token",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "device_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.GetTerminalNoRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
