<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.GetTerminalNoResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/GetTerminalNoResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getTerminalNo()
 * @method void setTerminalNo(\string $value)
 */
class GetTerminalNoResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sync.GetTerminalNoResponse)
  
  /**
   * @var string $terminal_no
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $terminal_no;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sync.GetTerminalNoResponse)

  // @@protoc_insertion_point(class_scope:.service.message.sync.GetTerminalNoResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "terminal_no",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.GetTerminalNoResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
