<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.Operation)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/Operation.proto
 *
 */
class Operation extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.service.message.sync.Operation)
  
  const SELECT = 1;
  const UPDATE = 2;
  const DELETE = 3;
  const INSERT = 4;
  
  // @@protoc_insertion_point(const_scope:.service.message.sync.Operation)
  
  // @@protoc_insertion_point(class_scope:.service.message.sync.Operation)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::SELECT,
        "name"  => 'SELECT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::UPDATE,
        "name"  => 'UPDATE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::DELETE,
        "name"  => 'DELETE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::INSERT,
        "name"  => 'INSERT',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.Operation)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
