<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.RecoveryRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/RecoveryRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getCustomerId()
 * @method void setCustomerId(\string $value)
 * @method string getAuthToken()
 * @method void setAuthToken(\string $value)
 * @method array getTable()
 * @method void appendTable(\service\message\sync\Table $value)
 */
class RecoveryRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sync.RecoveryRequest)
  
  /**
   * @var string $customer_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $customer_id;
  
  /**
   * @var string $auth_token
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $auth_token;
  
  /**
   * @var array $table
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \service\message\sync\Table
   **/
  protected $table;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sync.RecoveryRequest)

  // @@protoc_insertion_point(class_scope:.service.message.sync.RecoveryRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "customer_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "auth_token",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "table",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\sync\Table',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.RecoveryRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
