<?php
namespace service\message\sync;

// @@protoc_insertion_point(namespace:.service.message.sync.UpdateResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: sync/UpdateResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\sync\Job getJob()
 * @method void setJob(\service\message\sync\Job $value)
 * @method string getVersion()
 * @method void setVersion(\string $value)
 * @method string getLatestVersion()
 * @method void setLatestVersion(\string $value)
 */
class UpdateResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.sync.UpdateResponse)
  
  /**
   * @var \service\message\sync\Job $job
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $job;
  
  /**
   * @var string $version
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $version;
  
  /**
   * @var string $latest_version
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $latest_version;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.sync.UpdateResponse)

  // @@protoc_insertion_point(class_scope:.service.message.sync.UpdateResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "job",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\sync\Job',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "version",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "latest_version",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.sync.UpdateResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
