<?php
namespace service\message\driver;

// @@protoc_insertion_point(namespace:.service.message.driver.OrderActionResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: driver/OrderActionResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method \service\message\common\Message getMessage()
 * @method void setMessage(\service\message\common\Message $value)
 * @method \service\message\driver\DriverOrder getOrder()
 * @method void setOrder(\service\message\driver\DriverOrder $value)
 */
class OrderActionResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.driver.OrderActionResponse)
  
  /**
   * @var \service\message\common\Message $message
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $message;
  
  /**
   * @var \service\message\driver\DriverOrder $order
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $order;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.driver.OrderActionResponse)

  // @@protoc_insertion_point(class_scope:.service.message.driver.OrderActionResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "message",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\common\Message',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "order",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\service\message\driver\DriverOrder',
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.driver.OrderActionResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
