<?php
namespace service\message\driver;

// @@protoc_insertion_point(namespace:.service.message.driver.SearchOrderRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: driver/SearchOrderRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getDriverId()
 * @method void setDriverId(\string $value)
 * @method string getAuthToken()
 * @method void setAuthToken(\string $value)
 * @method string getFuzzyIncrementId()
 * @method void setFuzzyIncrementId(\string $value)
 */
class SearchOrderRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.driver.SearchOrderRequest)
  
  /**
   * @var string $driver_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $driver_id;
  
  /**
   * @var string $auth_token
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $auth_token;
  
  /**
   * @var string $fuzzy_increment_id
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $fuzzy_increment_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.driver.SearchOrderRequest)

  // @@protoc_insertion_point(class_scope:.service.message.driver.SearchOrderRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "driver_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "auth_token",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "fuzzy_increment_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.driver.SearchOrderRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
